### ISSUE TITLE
Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by paulbhartzog** [MScottBlake/select-line#7]
**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [select-line](https://github.com/MitchelSBlake/select-line) package, v0.16.0
### Stack Trace

Failed to activate the select-line package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/paulbhartzog/.atom/packages/select-line/lib/select-line.coffee:3:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61

```
### Commands

```
     -0:00.7.0 click (div.header.list-item)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "tree-view-open-files",
      "save-session"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.2
angularjs-styleguide-snippets, v0.7.0
docblockr, v0.7.2
file-icons, v1.5.7
javascript-snippets, v1.0.0
jshint, v1.3.7
linter-csslint, v0.0.13
linter-jsonlint, v0.1.4
linter-scss-lint, v1.0.4
minimap, v4.9.4
project-manager, v1.15.8
select-line, v0.16.0
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.0
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by paulbhartzog** [comment]
possible duplicate of https://github.com/MScottBlake/select-line/issues/6
